/*
Economy API

Testing InventoryAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package unityeconomy

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/liu1700/unityeconomy"
)

func Test_unityeconomy_InventoryAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test InventoryAPIService AddInventoryItem", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var playerId string

		resp, httpRes, err := apiClient.InventoryAPI.AddInventoryItem(context.Background(), projectId, playerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InventoryAPIService DeleteInventoryItem", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var playerId string
		var playersInventoryItemId string

		httpRes, err := apiClient.InventoryAPI.DeleteInventoryItem(context.Background(), projectId, playerId, playersInventoryItemId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InventoryAPIService GetPlayerInventory", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var playerId string

		resp, httpRes, err := apiClient.InventoryAPI.GetPlayerInventory(context.Background(), projectId, playerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InventoryAPIService UpdateInventoryItem", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var playerId string
		var playersInventoryItemId string

		resp, httpRes, err := apiClient.InventoryAPI.UpdateInventoryItem(context.Background(), projectId, playerId, playersInventoryItemId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
